// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIl8exNP82ktse8uVoAOean9WvuC_knw',
    appId: '1:524739663778:web:061a4727f68d8c9ee5c4fb',
    messagingSenderId: '524739663778',
    projectId: 'todo-app-ba23b',
    authDomain: 'todo-app-ba23b.firebaseapp.com',
    storageBucket: 'todo-app-ba23b.appspot.com',
    measurementId: 'G-2GCXD3RJ30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy27JqphQWYMrVPG0LhzdaZ8ychk2ItpA',
    appId: '1:524739663778:android:679824a0cf235da0e5c4fb',
    messagingSenderId: '524739663778',
    projectId: 'todo-app-ba23b',
    storageBucket: 'todo-app-ba23b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4V6b3WP2ZN7gWwZT7x4RfVcOeBoEMCEU',
    appId: '1:524739663778:ios:7476ec373b353688e5c4fb',
    messagingSenderId: '524739663778',
    projectId: 'todo-app-ba23b',
    storageBucket: 'todo-app-ba23b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4V6b3WP2ZN7gWwZT7x4RfVcOeBoEMCEU',
    appId: '1:524739663778:ios:7476ec373b353688e5c4fb',
    messagingSenderId: '524739663778',
    projectId: 'todo-app-ba23b',
    storageBucket: 'todo-app-ba23b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzIl8exNP82ktse8uVoAOean9WvuC_knw',
    appId: '1:524739663778:web:73e380124c1c2c2fe5c4fb',
    messagingSenderId: '524739663778',
    projectId: 'todo-app-ba23b',
    authDomain: 'todo-app-ba23b.firebaseapp.com',
    storageBucket: 'todo-app-ba23b.appspot.com',
    measurementId: 'G-XMG6TH5YEV',
  );
}
